import type { ThemeDraft } from '@silk/ui/themes/presets';

export const preset: ThemeDraft = {
	slug: 'default',
	name: 'Default',
	description: 'A custom theme published from the Silk UI Theme Studio.',
	publisher: 'Silk UI',
	fontSans: '"IBM Plex Sans", sans-serif',
	fontMono: '"SF Mono", monospace',
	fontHeader: '"IBM Plex Sans", sans-serif',
	radiusBase: '0.45rem',
	radiusSm: '0.21rem',
	radiusMd: '0.45rem',
	radiusLg: '0.55rem',
	radiusXl: '0.67rem',
	primaryButtonOutline: true,
	invertedPanels: false,
	fancyButtons: true,
	fancyBadges: true,
	fancyShadows: true,
	hapticPress: true,
	spacing: {
		buttonPaddingX: 13,
		badgePaddingX: 10,
		badgePaddingY: 4,
		cardPadding: 23,
		panelPadding: 10,
		fieldPaddingX: 12,
		menuItemPaddingX: 6,
		buttonHeight: 36,
		buttonHeightSm: 32,
		buttonHeightLg: 40,
		fieldHeight: 36,
		menuItemHeight: 32,
		switchTrackWidth: 40,
		switchThumbSize: 17,
		iconButtonSize: 32,
		menuPadding: 3,
		menuSearchPadding: 12,
		menuLabelPaddingX: 8,
		menuLabelPaddingY: 4,
		togglePaddingSm: 8,
		togglePaddingMd: 10,
		togglePaddingLg: 14,
		tabsTriggerPaddingX: 14,
		tabsTriggerPaddingY: 6,
		tabsListPadding: 3,
		toastPaddingX: 16,
		toastPaddingY: 16,
		calendarPadding: 12,
		colorPickerPadding: 10,
		sheetHeaderPaddingBottom: 24,
		modalPadding: 16,
		modalTitleDescriptionGap: 6,
		modalSectionGap: 16,
		sheetBodyPadding: 16
	},
	durationPreset: 'instant',
	motion: {
		hoverDuration: '120ms',
		menuDuration: '90ms',
		panelDuration: '170ms',
		sheetDuration: '210ms',
		overlayDuration: '100ms',
		tooltipDuration: '90ms',
		toastInDuration: '280ms',
		toastOutDuration: '220ms',
		panelX: 0,
		panelY: 5,
		panelBlur: 0,
		panelScaleStart: 1,
		sheetOffset: 132,
		overlayBlur: 0,
		panelEasing: 'cubic-bezier(0.34,1.56,0.64,1)'
	},
	light: {
		background: '#ffffff',
		border: '#e2e3e5',
		borderStrong: '#babdc4',
		input: '#babdc4',
		primary: '#2563eb',
		info: '#5383ed',
		foregroundOpposite: '#ffffff',
		foreground: '#19253e',
		muted: '#ffffff',
		panel: '#ffffff',
		modal: '#ffffff',
		foregroundMuted: '#707887',
		foregroundButton: '#ffffff',
		secondary: '#f4f4f5',
		card: '#ffffff',
		accent: '#f7fafe',
		alternate: '#2b364d',
		success: '#4bb673',
		warning: '#de9036',
		error: '#e14f4f',
		destructive: '#c23f3f',
		overlay: 'rgb(25 37 62 / 0.18)',
		ring: 'rgb(37 99 235 / 0.2)'
	},
	dark: {
		background: '#141414',
		border: '#404040',
		borderStrong: '#6c6d6e',
		input: '#6c6d6e',
		primary: '#447aee',
		info: '#5788c8',
		foregroundOpposite: '#09090b',
		foreground: '#f0f4f9',
		muted: '#181818',
		panel: '#2c2c2d',
		modal: '#303031',
		foregroundMuted: '#aaacb0',
		foregroundButton: '#ffffff',
		secondary: '#3f3f46',
		card: '#232324',
		accent: '#282f40',
		alternate: '#cdd0d4',
		success: '#47ae6f',
		warning: '#c69b2e',
		error: '#c46365',
		destructive: '#c54344',
		overlay: 'rgb(0 0 0 / 0.62)',
		ring: 'rgb(68 122 238 / 0.2)'
	},
	typography: {
		weightHeader: 500,
		weightBody: 400,
		weightLabel: 500,
		weightButton: 500,
		weightBadge: 500,
		trackingHeader: -0.01,
		trackingBody: 0,
		trackingLabel: 0,
		trackingButton: 0,
		trackingBadge: 0,
		sizeHeader: 20,
		sizeBody: 16,
		sizeLabel: 14,
		sizeButton: 14,
		sizeBadge: 12
	},
	overlaysOnSurface: false,
	pointerCursor: false
};
